buildscript {
	ext.versions = [
			'minSdk'        : 14,
			'compileSdk'    : 33,
			'buildTools'    : '33.0.0',
			'supportLibrary': '1.6.1'
	]

	ext.deps = [
			'support'    : [
					'annotations': "androidx.annotation:annotation:1.6.0",
					'appcompat'  : "androidx.appcompat:appcompat:1.6.1",
					'design'     : "com.google.android.material:material:1.8.0",
					'test'       : [
							'espresso': 'androidx.test.espresso:espresso-core:3.5.1',
							'runner'  : 'androidx.test:runner:1.5.2',
							'rules'   : 'androidx.test:rules:1.5.0',
					]
			],
			'junit'      : 'junit:junit:4.13.2',
			'assertj'    : 'org.assertj:assertj-core:3.24.2',
			'mockito'    : 'org.mockito:mockito-core:5.3.1',
			'robolectric': 'org.robolectric:robolectric:4.10.3',
			'antTasks'   : 'org.apache.maven:maven-ant-tasks:2.1.3',
	]

	dependencies {
		classpath 'com.android.tools.build:gradle:8.0.0'
		classpath 'com.github.ben-manes:gradle-versions-plugin:0.46.0'
	}

	repositories {
		gradlePluginPortal()
		mavenCentral()
		google()
	}
}

apply plugin: 'com.github.ben-manes.versions'

subprojects {
	repositories {
		mavenCentral()
		google()
	}

	afterEvaluate { project ->
		if (project.plugins.hasPlugin('android') || project.plugins.hasPlugin('com.android.library')) {
			android {
				lintOptions {
					quiet false
					textReport true
					textOutput 'stdout'
				}
			}
		}
	}

	configurations.all {
		resolutionStrategy {
			eachDependency { details ->
				// Force all of the primary support libraries to use the same version.
				if (details.requested.group == 'com.android.support') {
					details.useVersion versions.supportLibrary
				}
			}
		}
	}
}
