plugins {
	id 'com.android.library'
	id 'maven-publish'
}

android {
	namespace 'flow.basic'
	compileSdkVersion versions.compileSdk
	buildToolsVersion versions.buildTools

	defaultConfig {
		minSdkVersion versions.minSdk
		versionName VERSION_NAME
	}
	publishing {
		singleVariant("release")
	}
}

dependencies {
	implementation deps.support.annotations
	testImplementation deps.junit
	testImplementation deps.assertj
	testImplementation deps.mockito
	testImplementation deps.robolectric
	testImplementation deps.antTasks
}

afterEvaluate {
	publishing {
		publications {
			release(MavenPublication) {
				from components["release"]

				groupId = GROUP
				artifactId = POM_ARTIFACT_ID
				version = VERSION_NAME

				pom {
					name.set(POM_NAME)
					description.set(POM_DESCRIPTION)
					url.set(POM_URL)
				}
			}
		}
	}
}